# Services: define the containers/services used by the application
services:

  database:
    image: postgres:18
    container_name: agoraflowdb_container
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: agoraflow
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql

  redis_database:
    image: redis:7
    container_name: agoraflow_redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ./backend
    container_name: agoraflow_celery_worker
    command: celery -A src.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis_database
      - database

# Volumes: define persistent storage used by the services
volumes:
  postgres_data: