"""add unique contraints to registrations table

Revision ID: 66a4a5a9dd7e
Revises: dff613311617
Create Date: 2026-09-26 16:00:06.415110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a4a5a9dd7e'
down_revision: Union[str, Sequence[str], None] = 'dff613311617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_registration_user_event', 'registrations', ['user_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_registration_user_event', 'registrations', type_='unique')
    # ### end Alembic commands ###
